from fastapi import APIRouter, Depends, Request

from app.system.logic.menu_logic import MenuLogic
from senweaver.auth.security import requires_user
from senweaver.utils.response import ResponseBase, success_response

from ..system import module

router = APIRouter(tags=["菜单路由"], route_class=module.route_class)


@router.get("/routes", summary="获取菜单路由")
@requires_user()
async def get_routes(request: Request) -> ResponseBase:
    menus, auths = await MenuLogic.get_routes(request)
    menus1 = [
        {
            "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
            "name": "system",
            "rank": 1,
            "path": "/system",
            "component": "",
            "meta": {
                "title": "menus.sysManagement",
                "icon": "ep:setting",
                "showParent": False,
                "showLink": True,
                "extraIcon": "",
                "keepAlive": False,
                "frameSrc": "",
                "frameLoading": False,
                "transition": {"enterTransition": "", "leaveTransition": ""},
                "hiddenTag": False,
                "dynamicLevel": 0,
                "fixedTag": False,
            },
            "parent": None,
            "children": [
                {
                    "id": "4f9726d3-3796-4602-a716-1337ee2a168e",
                    "name": "SystemUser",
                    "rank": 2,
                    "path": "/system/user/index",
                    "component": "system/user/index",
                    "meta": {
                        "title": "menus.userManagement",
                        "icon": "ep:user",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                },
                {
                    "id": "8c6f0f01-a29e-4d72-96a8-abf67a4ede65",
                    "name": "SystemDept",
                    "rank": 14,
                    "path": "/system/dept/index",
                    "component": "system/dept/index",
                    "meta": {
                        "title": "menus.deptManagement",
                        "icon": "ri:group-line",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                },
                {
                    "id": "4f569df2-6149-462f-ad50-27f24370f5e2",
                    "name": "SystemMenu",
                    "rank": 23,
                    "path": "/system/menu/index",
                    "component": "system/menu/index",
                    "meta": {
                        "title": "menus.menuManagement",
                        "icon": "ep:menu",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                },
                {
                    "id": "1e11bae7-8002-4e92-a215-9eb4d3e8876c",
                    "name": "config",
                    "rank": 34,
                    "path": "/system/configs",
                    "component": "",
                    "meta": {
                        "title": "menus.configManagement",
                        "icon": "ep:connection",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                    "children": [
                        {
                            "id": "6e914168-2d0e-4a35-98c1-1543cb2c2fb7",
                            "name": "SystemConfig",
                            "rank": 35,
                            "path": "/system/config/system/index",
                            "component": "system/config/system/index",
                            "meta": {
                                "title": "menus.systemConfigManagement",
                                "icon": "ep:data-analysis",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "1e11bae7-8002-4e92-a215-9eb4d3e8876c",
                                "name": "config",
                                "label": "1e11bae7-8002-4e92-a215-9eb4d3e8876c",
                            },
                        },
                        {
                            "id": "09523de8-58de-4aa3-8732-a30da14443d4",
                            "name": "SystemUserConfig",
                            "rank": 44,
                            "path": "/system/config/user/index",
                            "component": "system/config/user/index",
                            "meta": {
                                "title": "menus.userConfigManagement",
                                "icon": "ep:data-line",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "1e11bae7-8002-4e92-a215-9eb4d3e8876c",
                                "name": "config",
                                "label": "1e11bae7-8002-4e92-a215-9eb4d3e8876c",
                            },
                        },
                    ],
                    "count": 2,
                },
                {
                    "id": "96772790-53e4-4113-b1d1-10998fe2f616",
                    "name": "permissions",
                    "rank": 53,
                    "path": "/system/permissions",
                    "component": "",
                    "meta": {
                        "title": "menus.permissionManagement",
                        "icon": "ep:lock",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                    "children": [
                        {
                            "id": "b5f6aa93-62dd-433f-9759-2f542baae423",
                            "name": "SystemRole",
                            "rank": 54,
                            "path": "/system/role/index",
                            "component": "system/role/index",
                            "meta": {
                                "title": "menus.roleManagement",
                                "icon": "ep:scale-to-original",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "96772790-53e4-4113-b1d1-10998fe2f616",
                                "name": "permissions",
                                "label": "96772790-53e4-4113-b1d1-10998fe2f616",
                            },
                        },
                        {
                            "id": "0678cc57-f292-4287-887b-ffade834dde1",
                            "name": "SystemDataPermission",
                            "rank": 63,
                            "path": "/system/permission/index",
                            "component": "system/permission/index",
                            "meta": {
                                "title": "menus.dataPermissionManagement",
                                "icon": "ep:refrigerator",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "96772790-53e4-4113-b1d1-10998fe2f616",
                                "name": "permissions",
                                "label": "96772790-53e4-4113-b1d1-10998fe2f616",
                            },
                        },
                        {
                            "id": "de2bdbf8-aeaf-4171-b73e-17cc383298d2",
                            "name": "SystemModelLabelField",
                            "rank": 71,
                            "path": "/system/field/index",
                            "component": "system/field/index",
                            "meta": {
                                "title": "menus.modelFieldManagement",
                                "icon": "ep:office-building",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "96772790-53e4-4113-b1d1-10998fe2f616",
                                "name": "permissions",
                                "label": "96772790-53e4-4113-b1d1-10998fe2f616",
                            },
                        },
                    ],
                    "count": 3,
                },
                {
                    "id": "74defdba-9645-439a-bf36-c0545bb9cda1",
                    "name": "logs",
                    "rank": 75,
                    "path": "/system/logs",
                    "component": "",
                    "meta": {
                        "title": "menus.logManagement",
                        "icon": "ep:files",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                    "children": [
                        {
                            "id": "33662086-715b-4478-b60d-a346c8c4f66b",
                            "name": "SystemOperationLog",
                            "rank": 76,
                            "path": "/system/logs/operation/index",
                            "component": "system/logs/operation/index",
                            "meta": {
                                "title": "menus.operationLogManagement",
                                "icon": "ep:document",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "74defdba-9645-439a-bf36-c0545bb9cda1",
                                "name": "logs",
                                "label": "74defdba-9645-439a-bf36-c0545bb9cda1",
                            },
                        },
                        {
                            "id": "45b14edf-5f9e-4ec8-bc4d-3c6f0b9c851b",
                            "name": "SystemUserLoginLog",
                            "rank": 81,
                            "path": "/system/logs/login/index",
                            "component": "system/logs/login/index",
                            "meta": {
                                "title": "menus.loginLogManagement",
                                "icon": "ep:cellphone",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "74defdba-9645-439a-bf36-c0545bb9cda1",
                                "name": "logs",
                                "label": "74defdba-9645-439a-bf36-c0545bb9cda1",
                            },
                        },
                    ],
                    "count": 2,
                },
                {
                    "id": "864eba5d-f793-4a9c-b7eb-cdb227a9d221",
                    "name": "systemNoticeDir",
                    "rank": 86,
                    "path": "/system/notice/",
                    "component": "system/notify/index",
                    "meta": {
                        "title": "menus.noticeAndAnnouncement",
                        "icon": "ep:copy-document",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                    "children": [
                        {
                            "id": "7008bb48-18b1-4bc1-a2ea-c22998024721",
                            "name": "SystemNotice",
                            "rank": 87,
                            "path": "/system/notice/index",
                            "component": "system/notice/index",
                            "meta": {
                                "title": "menus.newsAndAnnouncement",
                                "icon": "ep:message",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "864eba5d-f793-4a9c-b7eb-cdb227a9d221",
                                "name": "systemNoticeDir",
                                "label": "864eba5d-f793-4a9c-b7eb-cdb227a9d221",
                            },
                        },
                        {
                            "id": "b8664880-b2dd-48d9-ad88-c79258156084",
                            "name": "SystemNoticeRead",
                            "rank": 95,
                            "path": "/system/notice/read/list",
                            "component": "system/notice/read/list",
                            "meta": {
                                "title": "menus.readNotice",
                                "icon": "ep:cellphone",
                                "showParent": False,
                                "showLink": True,
                                "extraIcon": "",
                                "keepAlive": False,
                                "frameSrc": "",
                                "frameLoading": False,
                                "transition": {
                                    "enterTransition": "",
                                    "leaveTransition": "",
                                },
                                "hiddenTag": False,
                                "dynamicLevel": 0,
                                "fixedTag": False,
                            },
                            "parent": {
                                "id": "864eba5d-f793-4a9c-b7eb-cdb227a9d221",
                                "name": "systemNoticeDir",
                                "label": "864eba5d-f793-4a9c-b7eb-cdb227a9d221",
                            },
                        },
                    ],
                    "count": 2,
                },
                {
                    "id": "56e7a4c2-97ec-42b1-a8a9-54c3f4e488f3",
                    "name": "SystemUploadFile",
                    "rank": 100,
                    "path": "/system/file/index",
                    "component": "system/file/index",
                    "meta": {
                        "title": "menus.uploadFileManagement",
                        "icon": "ri:file-cloud-line",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                },
                {
                    "id": "53e1896e-dbf1-49aa-85b3-1711e27477ee",
                    "name": "search",
                    "rank": 111,
                    "path": "/system/search",
                    "component": "",
                    "meta": {
                        "title": "数据查询",
                        "icon": "ep:data-line",
                        "showParent": False,
                        "showLink": False,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                        "name": "system",
                        "label": "050f7e13-cf60-4c1d-b791-3ab6a97254f6",
                    },
                },
            ],
            "count": 9,
        },
        {
            "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
            "name": "settings",
            "rank": 116,
            "path": "/settings",
            "component": "",
            "meta": {
                "title": "menus.systemSettings",
                "icon": "ep:set-up",
                "showParent": False,
                "showLink": True,
                "extraIcon": "",
                "keepAlive": False,
                "frameSrc": "",
                "frameLoading": False,
                "transition": {"enterTransition": "", "leaveTransition": ""},
                "hiddenTag": False,
                "dynamicLevel": 0,
                "fixedTag": False,
            },
            "parent": None,
            "children": [
                {
                    "id": "98b2b6ce-348e-4717-9140-204646324978",
                    "name": "SettingBasic",
                    "rank": 117,
                    "path": "/settings/basic",
                    "component": "settings/basic",
                    "meta": {
                        "title": "menus.basicSettings",
                        "icon": "ep:money",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "4101963c-050f-4ee6-bd59-e9ec0c0fb98b",
                    "name": "SettingRegister",
                    "rank": 120,
                    "path": "/settings/register",
                    "component": "settings/register",
                    "meta": {
                        "title": "menus.registerSettings",
                        "icon": "ep:set-up",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "4c5c555d-90ad-42c3-9186-6a8fe48c0d38",
                    "name": "SettingLogin",
                    "rank": 123,
                    "path": "/settings/login",
                    "component": "settings/login",
                    "meta": {
                        "title": "menus.loginSettings",
                        "icon": "ep:iphone",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "55a70142-5f7c-4d35-97b0-b7e09c6d4e42",
                    "name": "SettingReset",
                    "rank": 131,
                    "path": "/settings/reset",
                    "component": "settings/reset",
                    "meta": {
                        "title": "menus.resetSettings",
                        "icon": "ep:folder-remove",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "d441eb43-590e-4b76-a290-2d00d2376089",
                    "name": "SettingPassword",
                    "rank": 134,
                    "path": "/settings/password",
                    "component": "settings/password",
                    "meta": {
                        "title": "menus.passwordSettings",
                        "icon": "ep:postcard",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "9b620250-71f2-4b36-8de6-55ac3ae2ad5e",
                    "name": "SettingEmail",
                    "rank": 137,
                    "path": "/settings/email",
                    "component": "settings/email",
                    "meta": {
                        "title": "menus.emailSettings",
                        "icon": "ep:scale-to-original",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "772071fa-7053-447b-b86d-8c91a76a0e94",
                    "name": "SettingSms",
                    "rank": 141,
                    "path": "/settings/sms",
                    "component": "settings/sms",
                    "meta": {
                        "title": "menus.smsSettings",
                        "icon": "ep:chat-line-square",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "8875abd9-241b-4ac6-8616-24c8378d6037",
                    "name": "SettingVerify",
                    "rank": 148,
                    "path": "/settings/verify",
                    "component": "settings/verify",
                    "meta": {
                        "title": "menus.verifySettings",
                        "icon": "ep:memo",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
                {
                    "id": "2cd0f34f-498a-43ca-a00e-f529b7ed4da2",
                    "name": "SettingBind",
                    "rank": 153,
                    "path": "/settings/bind",
                    "component": "settings/bind",
                    "meta": {
                        "title": "menus.bindSettings",
                        "icon": "ep:scale-to-original",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": {
                        "id": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                        "name": "settings",
                        "label": "ea094317-8c50-429c-90a6-17dc3c8b366c",
                    },
                },
            ],
            "count": 9,
        },
        {
            "path": "/default/user/info/index",
            "title": None,
            "meta": {
                "icon": "ep:avatar",
                "title": "menus.personalCenter",
                "rank": None,
                "showLink": False,
            },
            "children": [
                {
                    "id": "6997ffe2-8246-401d-8800-248ecbc2dd83",
                    "name": "UserInfo",
                    "rank": 158,
                    "path": "/user/info/index",
                    "component": "",
                    "meta": {
                        "title": "menus.personalCenter",
                        "icon": "ep:avatar",
                        "showParent": False,
                        "showLink": False,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": None,
                }
            ],
        },
        {
            "path": "/default/user/notice/index",
            "title": None,
            "meta": {
                "icon": "ep:notification",
                "title": "menus.messageCenter",
                "rank": None,
                "showLink": True,
            },
            "children": [
                {
                    "id": "e9e2e5c4-3735-4219-af09-1e0f3e5118d8",
                    "name": "UserNotice",
                    "rank": 164,
                    "path": "/user/notice/index",
                    "component": "user/notice/index",
                    "meta": {
                        "title": "menus.messageCenter",
                        "icon": "ep:notification",
                        "showParent": False,
                        "showLink": True,
                        "extraIcon": "",
                        "keepAlive": False,
                        "frameSrc": "",
                        "frameLoading": False,
                        "transition": {"enterTransition": "", "leaveTransition": ""},
                        "hiddenTag": False,
                        "dynamicLevel": 0,
                        "fixedTag": False,
                    },
                    "parent": None,
                }
            ],
        },
    ]
    auths1 = [
        "batchDelete:SettingBlockIp",
        "delete:SettingBlockIp",
        "list:SettingBlockIp",
        "update:SettingBindPhone",
        "detail:SettingBindPhone",
        "update:SettingBindEmail",
        "detail:SettingBindEmail",
        "list:userLoginLog",
        "bind:UserInfo",
        "update:settingCaptcha",
        "detail:settingCaptcha",
        "update:SettingReset",
        "detail:SettingReset",
        "update:SettingVerify",
        "detail:SettingVerify",
        "test:SettingSmsConfig",
        "update:SettingSmsConfig",
        "detail:SettingSmsConfig",
        "list:SettingSmsBackends",
        "test:SettingEmail",
        "update:SettingSms",
        "detail:SettingSms",
        "update:SettingEmail",
        "detail:SettingEmail",
        "update:SettingPassword",
        "detail:SettingPassword",
        "update:SettingRegisterAuth",
        "detail:SettingRegisterAuth",
        "update:SettingLoginLimit",
        "detail:SettingLoginLimit",
        "update:SettingLoginAuth",
        "detail:SettingLoginAuth",
        "update:SettingBasic",
        "detail:SettingBasic",
        "unBlock:systemUser",
        "config:systemUploadFile",
        "list:systemUploadFile",
        "delete:systemUploadFile",
        "upload:systemUploadFile",
        "batchDelete:systemUploadFile",
        "update:systemUploadFile",
        "create:systemUploadFile",
        "import:systemMenu",
        "export:systemMenu",
        "import:systemRole",
        "export:systemRole",
        "import:systemDataPermission",
        "export:systemDataPermission",
        "import:systemUserConfig",
        "export:systemUserConfig",
        "import:systemSystemConfig",
        "export:systemSystemConfig",
        "export:systemLoginLog",
        "export:systemOperationLog",
        "import:systemDept",
        "export:systemDept",
        "import:systemUser",
        "export:systemUser",
        "apiUrl:systemMenu",
        "list:systemSearchMenu",
        "list:systemSearchRole",
        "list:systemSearchDept",
        "list:systemSearchUser",
        "create:systemUser",
        "delete:systemUser",
        "update:systemUser",
        "list:systemUser",
        "create:systemRole",
        "delete:systemRole",
        "update:systemRole",
        "list:systemRole",
        "batchDelete:systemUser",
        "batchDelete:systemRole",
        "create:systemMenu",
        "delete:systemMenu",
        "update:systemMenu",
        "list:systemMenu",
        "batchDelete:systemMenu",
        "rank:systemMenu",
        "upload:systemUser",
        "delete:systemOperationLog",
        "list:systemOperationLog",
        "batchDelete:systemOperationLog",
        "empower:systemUser",
        "reset:systemUser",
        "list:systemNotice",
        "delete:systemNotice",
        "batchDelete:systemNotice",
        "create:systemNotice",
        "update:systemNotice",
        "update:systemNoticePublish",
        "list:systemNoticeRead",
        "delete:systemNoticeRead",
        "batchDelete:systemNoticeRead",
        "update:UserInfo",
        "upload:UserInfo",
        "reset:UserInfo",
        "update:systemNoticeReadState",
        "list:userNotice",
        "update:userNoticeRead",
        "update:userNoticeReadAll",
        "list:systemDept",
        "create:systemDept",
        "delete:systemDept",
        "update:systemDept",
        "batchDelete:systemDept",
        "empower:systemDept",
        "list:systemDataPermission",
        "create:systemDataPermission",
        "delete:systemDataPermission",
        "update:systemDataPermission",
        "batchDelete:systemDataPermission",
        "create:systemAnnouncement",
        "list:systemLoginLog",
        "delete:systemLoginLog",
        "batchDelete:systemLoginLog",
        "list:systemSystemConfig",
        "create:systemSystemConfig",
        "delete:systemSystemConfig",
        "update:systemSystemConfig",
        "batchDelete:systemSystemConfig",
        "invalid:systemSystemConfig",
        "list:systemModelField",
        "list:systemModelFieldLookups",
        "list:systemUserConfig",
        "create:systemUserConfig",
        "delete:systemUserConfig",
        "update:systemUserConfig",
        "batchDelete:systemUserConfig",
        "invalid:systemUserConfig",
        "sync:systemModelField",
        "detail:systemRole",
        "permissions:systemMenu",
    ]
    return success_response(auths=auths, data=menus)
